[install]
# Use faster package resolution
cache = true
# Use exact versions for better caching
exact = true
# Enable production optimizations
production = false

[install.scopes]
# Configure scopes for better performance
"@babel" = "https://registry.npmjs.org"
"@vue" = "https://registry.npmjs.org"
"@web3-onboard" = "https://registry.npmjs.org"

[run]
# Enable Bun's native bundler for faster builds
bun = true

[test]
# Configure test settings if needed
timeout = 30000