name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

env:
  BUN_VERSION: latest

jobs:
  # All jobs run in parallel - no dependencies!
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ env.BUN_VERSION }}
          
      - name: Cache deps
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-lint-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-lint-
            ${{ runner.os }}-bun-
            
      - name: Install deps
        run: bun install --frozen-lockfile
        
      - name: Lint
        run: bun run lint

  types:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ env.BUN_VERSION }}
          
      - name: Cache deps
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-types-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-types-
            ${{ runner.os }}-bun-
            
      - name: Install deps
        run: bun install --frozen-lockfile
        
      - name: Type check
        run: bun run type-check

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ env.BUN_VERSION }}
          
      - name: Cache deps
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-build-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-build-
            ${{ runner.os }}-bun-
            
      - name: Install deps
        run: bun install --frozen-lockfile
        
      - name: Build
        run: bun run build
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/
          retention-days: 1

  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ env.BUN_VERSION }}
          
      - name: Cache deps
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-audit-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-audit-
            ${{ runner.os }}-bun-
            
      - name: Install deps
        run: bun install --frozen-lockfile
        
      - name: Security audit
        run: bun run audit

  # Optional: Only run if we want to test analyze mode
  build-analyze:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ env.BUN_VERSION }}
          
      - name: Cache deps
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-analyze-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-analyze-
            ${{ runner.os }}-bun-
            
      - name: Install deps
        run: bun install --frozen-lockfile
        
      - name: Build analyze
        run: bun run build:analyze

  # Summary job to check all results
  success:
    runs-on: ubuntu-latest
    needs: [lint, types, build, audit, build-analyze]
    if: always()
    steps:
      - name: Check results
        run: |
          failed_jobs=()
          if [[ "${{ needs.lint.result }}" == "failure" ]]; then failed_jobs+=("lint"); fi
          if [[ "${{ needs.types.result }}" == "failure" ]]; then failed_jobs+=("types"); fi
          if [[ "${{ needs.build.result }}" == "failure" ]]; then failed_jobs+=("build"); fi
          if [[ "${{ needs.audit.result }}" == "failure" ]]; then failed_jobs+=("audit"); fi
          if [[ "${{ needs.build-analyze.result }}" == "failure" ]]; then failed_jobs+=("build-analyze"); fi
          
          if [ ${#failed_jobs[@]} -gt 0 ]; then
            echo "❌ CI failed on: ${failed_jobs[*]}"
            exit 1
          else
            echo "✅ All checks passed!"
          fi